### PR TITLE
Display periods in entry view

### LINKED ISSUE #93: Display periods in view.php
The association between entries and periods should be shown in view.php

### PR DESCRIPTION
**Pull request by UndeclaredVariable**
Resolves #93 

This adds a new column to the entries table that displays either 'No period', 'Current period', or the periodid.

### CODE REVIEW

**Comment by brendanheywood** [comment]
What is the feature you are trying to add here?

I'm not sure this is the best way to expose the period, the period id is meaningless to an end user, the only thing that really matters to them are the period dates. My natural inclination is to have each period broken up into sections and each section has its own heading and table. very roughly something like:

## 2021

- table row 1
- table row 2

## 2020
- table row 3
- table row 4
## 2019

**Comment by UndeclaredVariable** [comment]
I've tried changing it now so that there's a separate table for each period, with the the date range for the period displayed. Currently downloading a table will download every entry. Since the download functionality for tablelib uses an optional param 'download', as described [here](https://docs.moodle.org/dev/lib/tablelib.php#Adding_download_capability_to_existing_tables), there doesn't seem to be a simple way to tell which table was selected for downloading.

**Comment by brendanheywood** [comment]
I think downloading the lot is fine, and if you do that then you can join in the periods table and include the period start and ends dates as extra columns

**Comment by brendanheywood** [comment]
Also I think you can set the base url for the table which can include extra params which will get passed into the download

**Pull request merged**
